server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}/collinskube
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"