server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beyondfitt
    username: postgres
    password: postgres
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"